[package]
name = "execution_local_dll"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.52.0", features = ["Win32_Security","Win32_System_Threading","Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_LibraryLoader"] }